// Certain kill icons use the same images, so rather than having
// duplicate image files we just use aliases for them instead
export const KILL_ICON_ALIASES: { [key: string]: string } = {
  world: 'skull',
  player: 'skull',
  telefrag: 'skull',
  shotgun_pyro: 'shotgun',
  tf_projectile_pipe_remote: 'stickybomb_launcher',
  the_classic: 'classic',
  tf_projectile_arrow: 'huntsman',
  club: 'kukri',
  shotgun_primary: 'shotgun',
  shotgun_soldier: 'shotgun',
  shotgun_hwg: 'shotgun',
  pickaxe: 'escape_plan',
  tf_projectile_pipe: 'grenade_launcher',
  obj_sentrygun: 'sentrygun1',
  steel_fists: 'fists_of_steel',
  tf_projectile_rocket: 'rocket_launcher',
  obj_sentrygun3: 'sentrygun3',
  obj_sentrygun2: 'sentrygun2',
  worldspawn: 'skull',
  nonnonviolent_protest: 'conscientious_objector',
  deflect_promode: 'deflect_rocket',
  trigger_hurt: 'bleed',
  quake_rl: 'original',
  wrangler_kill: 'wrangler',
  obj_minisentry: 'minisentry',
  pistol_scout: 'pistol',
  bleed_kill: 'bleed',
  maxgun: 'lugermorph',
  rocketlauncher_directhit: 'direct_hit',
  frontier_kill: 'frontier_justice',
  robot_arm_kill: 'gunslinger',
  wrench_jag: 'jag',
  loose_cannon_explosion: 'loose_cannon',
  samrevolver: 'big_kill',
  long_heatmaker: 'huo-long_heater',
}
